# Generated by Django 5.1.6 on 2025-04-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_scholarship_myuser_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scholarship',
        ),
        migrations.AddField(
            model_name='myuser',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('applicant', 'Applicant'), ('reviewer', 'Reviewer'), ('donor', 'Donor'), ('admin', 'Admin')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('reviewer', 'Reviewer'), ('donor', 'Donor'), ('admin', 'Admin')], default='applicant', max_length=20),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role_approved',
            field=models.BooleanField(default=False),
        ),
    ]
