# Generated by Django 5.1.6 on 2025-04-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_scholarship_myuser_requested_role_myuser_role_and_more'),
        ('accounts', '0004_userchangehistory'),
    ]

    operations = [
    ]
