# Generated by Django 5.1.6 on 2025-04-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_scholarship_alter_myuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='gpa',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='major',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
