# Generated by Django 5.1.6 on 2025-03-26 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_remove_scholarship_apply_info_scholarship_donor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='founder',
        ),
    ]
