# Generated by Django 5.1.6 on 2025-04-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_remove_scholarship_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='required_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='required_major',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
